name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any



  cupertino_icons: ^0.1.2
  geolocator: ^5.1.5
  http: ^0.12.0+3
  flutter_spinkit: ^3.1.0
  mockito: ^4.1.1
  matcher: ^0.12.6



flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900